-- Local demonstration data only; never apply over a live catalog.
update sf_product set slug='linea-wardrobe',category='wardrobes',name_en='Linea wardrobe',name_zh='Linea 卧室衣柜',description_en='Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.',description_zh='为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。',specs_en='Finish: Powder coating
Configuration: Confirmed before production',specs_zh='表面处理：喷粉涂层
配置：生产前确认',image_url='/images/xj-wardrobe.jpg',model='XJ-W01',sort_order=0,variants='[{"code": "XJ-W01-1", "dimensions": "800 × 450 × 2000 mm", "colorEn": "Slate blue", "colorZh": "灰蓝色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-wardrobe.jpg"}, {"code": "XJ-W01-2", "dimensions": "1000 × 450 × 2000 mm", "colorEn": "Slate blue", "colorZh": "灰蓝色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-wardrobe.jpg"}]' where slug='linea-wardrobe';
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('linea-wardrobe-2','wardrobes','Linea wardrobe / Compact','Linea 卧室衣柜 · 紧凑款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-wardrobe-2.jpg','XJ-W02','','',true,1,'[{"code": "XJ-W02-1", "dimensions": "900 × 450 × 2000 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-wardrobe-2.jpg"}, {"code": "XJ-W02-2", "dimensions": "1100 × 450 × 2000 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-wardrobe-2.jpg"}]');
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('linea-wardrobe-3','wardrobes','Linea wardrobe / Extended','Linea 卧室衣柜 · 加宽款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-wardrobe-3.jpg','XJ-W03','','',true,2,'[{"code": "XJ-W03-1", "dimensions": "1000 × 450 × 2000 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-wardrobe-3.jpg"}, {"code": "XJ-W03-2", "dimensions": "1200 × 450 × 2000 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-wardrobe-3.jpg"}]');
update sf_product set slug='forma-sideboard',category='living',name_en='Forma sideboard',name_zh='Forma 家居柜',description_en='Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.',description_zh='为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。',specs_en='Finish: Powder coating
Configuration: Confirmed before production',specs_zh='表面处理：喷粉涂层
配置：生产前确认',image_url='/images/xj-living.jpg',model='XJ-L01',sort_order=3,variants='[{"code": "XJ-L01-1", "dimensions": "800 × 450 × 850 mm", "colorEn": "Oxblood", "colorZh": "酒红色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-living.jpg"}, {"code": "XJ-L01-2", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Oxblood", "colorZh": "酒红色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-living.jpg"}]' where slug='forma-sideboard';
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('forma-sideboard-2','living','Forma sideboard / Compact','Forma 家居柜 · 紧凑款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-living-2.jpg','XJ-L02','','',true,4,'[{"code": "XJ-L02-1", "dimensions": "900 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-living-2.jpg"}, {"code": "XJ-L02-2", "dimensions": "1100 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-living-2.jpg"}]');
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('forma-sideboard-3','living','Forma sideboard / Extended','Forma 家居柜 · 加宽款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-living-3.jpg','XJ-L03','','',true,5,'[{"code": "XJ-L03-1", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-living-3.jpg"}, {"code": "XJ-L03-2", "dimensions": "1200 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Cold-rolled steel", "materialZh": "冷轧钢", "moq": 10, "imageUrl": "/images/xj-living-3.jpg"}]');
update sf_product set slug='atelier-kitchen',category='kitchens',name_en='Atelier kitchen',name_zh='Atelier 橱柜',description_en='Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.',description_zh='为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。',specs_en='Finish: Powder coating
Configuration: Confirmed before production',specs_zh='表面处理：喷粉涂层
配置：生产前确认',image_url='/images/xj-kitchen.jpg',model='XJ-K01',sort_order=6,variants='[{"code": "XJ-K01-1", "dimensions": "800 × 450 × 850 mm", "colorEn": "Moss green / brushed steel", "colorZh": "苔原绿 / 拉丝钢", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-kitchen.jpg"}, {"code": "XJ-K01-2", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Moss green / brushed steel", "colorZh": "苔原绿 / 拉丝钢", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-kitchen.jpg"}]' where slug='atelier-kitchen';
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('atelier-kitchen-2','kitchens','Atelier kitchen / Compact','Atelier 橱柜 · 紧凑款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-kitchen-2.jpg','XJ-K02','','',true,7,'[{"code": "XJ-K02-1", "dimensions": "900 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-kitchen-2.jpg"}, {"code": "XJ-K02-2", "dimensions": "1100 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-kitchen-2.jpg"}]');
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('atelier-kitchen-3','kitchens','Atelier kitchen / Extended','Atelier 橱柜 · 加宽款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-kitchen-3.jpg','XJ-K03','','',true,8,'[{"code": "XJ-K03-1", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-kitchen-3.jpg"}, {"code": "XJ-K03-2", "dimensions": "1200 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-kitchen-3.jpg"}]');
update sf_product set slug='aqua-vanity',category='bathroom',name_en='Aqua vanity',name_zh='Aqua 浴室柜',description_en='Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.',description_zh='为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。',specs_en='Finish: Powder coating
Configuration: Confirmed before production',specs_zh='表面处理：喷粉涂层
配置：生产前确认',image_url='/images/xj-bathroom.jpg',model='XJ-B01',sort_order=9,variants='[{"code": "XJ-B01-1", "dimensions": "800 × 450 × 850 mm", "colorEn": "Sage green", "colorZh": "鼠尾草绿", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-bathroom.jpg"}, {"code": "XJ-B01-2", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Sage green", "colorZh": "鼠尾草绿", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-bathroom.jpg"}]' where slug='aqua-vanity';
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('aqua-vanity-2','bathroom','Aqua vanity / Compact','Aqua 浴室柜 · 紧凑款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-bathroom-2.jpg','XJ-B02','','',true,10,'[{"code": "XJ-B02-1", "dimensions": "900 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-bathroom-2.jpg"}, {"code": "XJ-B02-2", "dimensions": "1100 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-bathroom-2.jpg"}]');
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('aqua-vanity-3','bathroom','Aqua vanity / Extended','Aqua 浴室柜 · 加宽款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-bathroom-3.jpg','XJ-B03','','',true,11,'[{"code": "XJ-B03-1", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-bathroom-3.jpg"}, {"code": "XJ-B03-2", "dimensions": "1200 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-bathroom-3.jpg"}]');
update sf_product set slug='terra-outdoor',category='outdoor',name_en='Terra outdoor cabinet',name_zh='Terra 户外柜',description_en='Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.',description_zh='为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。',specs_en='Finish: Powder coating
Configuration: Confirmed before production',specs_zh='表面处理：喷粉涂层
配置：生产前确认',image_url='/images/xj-outdoor.jpg',model='XJ-O01',sort_order=12,variants='[{"code": "XJ-O01-1", "dimensions": "800 × 450 × 850 mm", "colorEn": "Graphite", "colorZh": "石墨灰", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-outdoor.jpg"}, {"code": "XJ-O01-2", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Graphite", "colorZh": "石墨灰", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-outdoor.jpg"}]' where slug='terra-outdoor';
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('terra-outdoor-2','outdoor','Terra outdoor cabinet / Compact','Terra 户外柜 · 紧凑款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-outdoor-2.jpg','XJ-O02','','',true,13,'[{"code": "XJ-O02-1", "dimensions": "900 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-outdoor-2.jpg"}, {"code": "XJ-O02-2", "dimensions": "1100 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-outdoor-2.jpg"}]');
insert into sf_product(slug,category,name_en,name_zh,description_en,description_zh,specs_en,specs_zh,image_url,model,name_ru,description_ru,published,sort_order,variants) values('terra-outdoor-3','outdoor','Terra outdoor cabinet / Extended','Terra 户外柜 · 加宽款','Metal cabinetry for everyday living. Design concept and sample specifications; final dimensions, finish and minimum order quantity are confirmed with your quotation.','为日常生活设计的金属柜。图片及规格为设计示例，最终尺寸、颜色和最小起订量以报价确认方案为准。','Finish: Powder coating
Configuration: Confirmed before production','表面处理：喷粉涂层
配置：生产前确认','/images/xj-outdoor-3.jpg','XJ-O03','','',true,14,'[{"code": "XJ-O03-1", "dimensions": "1000 × 450 × 850 mm", "colorEn": "Warm ivory", "colorZh": "暖象牙白", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-outdoor-3.jpg"}, {"code": "XJ-O03-2", "dimensions": "1200 × 450 × 850 mm", "colorEn": "Sand", "colorZh": "暖砂色", "materialEn": "Stainless steel", "materialZh": "不锈钢", "moq": 10, "imageUrl": "/images/xj-outdoor-3.jpg"}]');
update sf_content set en='Years ago, a friend about to get married showed us a photo of his parents'' wardrobe — after only five years it had cracked, its doors had warped, the back panel had darkened from moisture, and insects had left their marks. He asked us seriously whether any material could make a cabinet truly strong, durable and eco-friendly, without daily worry about damp, mould and insects.

He did not want to repeat his parents'' problem in his new home. We talked late into the night, and the answer turned out to be simple: if wood is the problem, remove the wood.

That is why we build cabinets entirely from stainless steel and cold-rolled steel — no wood at all — for wardrobes, kitchens, bathrooms and outdoor use.

That broken wardrobe is our origin, and still the direction we keep walking in: to bring strong, durable, eco-friendly metal cabinets into more homes.',zh='多年前，一个即将结婚的朋友找到我们，带来一块使用了五年就已经腐烂变形的木板柜板。他很慎重地问，是否有更好的材料，可以让家具柜子更加结实、耐用、环保，也不需要担心虫子的啃咬破坏。

那是他父母使用的衣柜，经过五年，已经出现开裂、变形、长虫等种种问题。他不希望自己的新家庭也遇到这样的情况，希望衣柜、橱柜更加健康、耐用、易打理。

我们一起聊了一夜，最终选择不锈钢和冷轧钢作为原材料，打造不使用任何木材的金属衣柜、橱柜。

这是我们的起点，也将是我们的使命：让耐用环保的家用柜走进千家万户。' where content_key='brand_story';
update sf_content set en='XingjiuCabinets creates metal cabinetry for the places we call home. From wardrobes and living-room storage to kitchens, bathrooms and outdoor spaces, we work with stainless steel and cold-rolled steel to make everyday storage feel considered and welcoming.',zh='XingjiuCabinets 专注家用金属柜，从卧室衣柜、家居收纳，到厨房、浴室与户外空间，以不锈钢和冷轧钢为材料，为日常生活打造温馨、实用的收纳。' where content_key='factory_intro';
update sf_content set en='Materials, dimensions, finishes and hardware are agreed before production. Share your drawings and quantities with us to discuss sampling, metal forming, surface finishing, assembly, inspection and packing. Capacity and delivery schedules are confirmed for each order.',zh='生产前逐项确认材料、尺寸、表面处理与五金配置。欢迎提供图纸和数量，沟通打样、金属成型、表面处理、组装、检验和包装。具体产能与交期按每个订单确认。' where content_key='factory_process';
update sf_content set en='A home, a collection, or a new project. Tell us the cabinet type, quantity, country and delivery city, and we will help you work through the details.',zh='无论是一个家、一组产品系列，还是新的项目，欢迎告诉我们柜类、数量、国家和交付城市，我们会与你一起确认细节。' where content_key='contact_intro';
